// <auto-generated />
namespace MailSender.lib.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RecipientAddComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecipientAddComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201906042045054_RecipientAddComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
